services:
  webb-tracker-api:
    build: .
    image: avatsaev/webb-tracker-api
    ports:
      - "8001:8001"
    links:
      - redis
#  redis:
#    image: redis
#volumes:
#  logvolume01: {}
