name: CI/CD webb tracker api

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/webb-tracker-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY  }}
          HOSTNAME : ${{ secrets.EC2_HOST  }}
          USER_NAME : ${{ secrets.EC2_USER  }}
          DOCKER_IMAGE: avatsaev/webb-tracker-api:latest

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker stop webb-tracker-api &&
            docker rm webb-tracker-api &&
            docker pull ${DOCKER_IMAGE} &&
            docker run -d --name webb-tracker-api -p 8001:8001 ${DOCKER_IMAGE}
          '
