name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Prepare some metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_HUB_USER }}/webb-tracker-api
          tags: type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy new Docker image on EC2 instances
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on EC2 instances
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY  }}
          HOSTNAME : ${{ secrets.EC2_HOST  }}
          USER_NAME : ${{ secrets.EC2_USER  }}
          SERVER_IPS: ${{ secrets.EC2_SERVER_IPS }}
          DOCKER_IMAGE: avatsaev/webb-tracker-api:latest
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          for serverIP in ${SERVER_IPS//,/ }
          do
           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${serverIP} '
            docker image prune -f
            docker stop webb-tracker-api &&
            docker rm webb-tracker-api &&
            docker pull avatsaev/webb-tracker-api &&
            docker run -d --name webb-tracker-api -p 8001:8001 avatsaev/webb-tracker-api
            docker image prune -f
          '
          done
         
